### ISSUE TITLE
pancake-frontend Failed to compile

### ISSUE THREAD

**Issue by luckyz20** [chobynleo/pancakeswap-frontend-hardhat-testnet#1]
when I start the pancake-frontend, and the path of this " ../../../deployments/31337" is right, the error info is as follows

```
Failed to compile.

./src/config/constants/contracts.ts
Module not found: You attempted to import ../../../deployments/31337/AnniversaryAchievement.json which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
```

**Comment by chobynleo** [comment]
> when I start the pancake-frontend, and the path of this " ../../../deployments/31337" is right, the error info is as follows
> 
> ```
> Failed to compile.
> 
> ./src/config/constants/contracts.ts
> Module not found: You attempted to import ../../../deployments/31337/AnniversaryAchievement.json which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
> ```

Comment out the ModuleScopePlugin command in webpack.config.dev.
see [44114436](https://stackoverflow.com/questions/44114436/the-create-react-app-imports-restriction-outside-of-src-directory?noredirect=1)

I've configure project, so you can re-download.
