### ISSUE TITLE
Multicall error

### ISSUE THREAD

**Issue by thapld** [chobynleo/pancakeswap-frontend-hardhat-testnet#2]
Error: call revert exception (method="aggregate((address,bytes)[])", errorArgs=["Multicall aggregate: call failed"], errorName="Error", errorSignature="Error(string)", reason="Multicall aggregate: call failed", code=CALL_EXCEPTION, version=abi/5.4.0)

Error: sending a transaction requires a signer (operation="sendTransaction", code=UNSUPPORTED_OPERATION, version=contracts/5.4.0)

**Comment by chobynleo** [comment]
> Error: call revert exception (method="aggregate((address,bytes)[])", errorArgs=["Multicall aggregate: call failed"], errorName="Error", errorSignature="Error(string)", reason="Multicall aggregate: call failed", code=CALL_EXCEPTION, version=abi/5.4.0)
> 
> Error: sending a transaction requires a signer (operation="sendTransaction", code=UNSUPPORTED_OPERATION, version=contracts/5.4.0)

I've configure project, so you can re-download.
Also, your problem looks like the wallet is not connected to the network.

**Comment by bnwgithub** [comment]
Thank you so much! Let me try.
