### ISSUE TITLE
Deploy on BSC testnet

### ISSUE THREAD

**Issue by crypt0inf0** [chobynleo/pancakeswap-frontend-hardhat-testnet#6]
Hi, How to deploy pancakeswap smart contract on BSC testnet instead of  local blockchain server?

**Comment by chobynleo** [comment]
Configuration to the BSC main network is the same as local testnet, see README.md.
I also deploy pancakeswap on heco mainnet.

**Comment by crypt0inf0** [comment]
Ok, Thanks.
